version: "3.3"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUX_DB: grafana
      INFLUXDB_USER: grafana
      INFLUXDB_USER_PASSWORD: password
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  jupyter:
    build: ./jupyter
    container_name: jupyter
    volumes:
        - ./jupyter:/home/docker_worker/jupyter
    ports:
        - 8891:8888
    command: "start-notebook.sh"
    user: root
    env_file:
    - './jupyter/.env'
    environment:
      NB_USER: docker_worker
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
